"""Finance-domain objects."""

from qfin.finance.alm import (
    ALMFactorAttribution,
    ALMFactorScenarioResult,
    ALMModel,
    ALMPathResult,
    ALMResult,
    ALMScenarioResult,
    ALMSensitivityReport,
    AssetPortfolio,
    LiabilityPortfolio,
    RebalancingStrategy,
)
from qfin.finance.calibration import (
    BondMarketQuote,
    BootstrapInstrument,
    BootstrapInstrumentResult,
    CurveBootstrapError,
    CurveBootstrapReport,
    Deposit,
    SimpleSwap,
    ZeroCouponInstrument,
    bootstrap_curve,
)
from qfin.finance.curves import (
    CurveDiagnostics,
    CurveExtrapolation,
    CurveInterpolation,
    CurveMarketQuote,
    YieldCurve,
)
from qfin.finance.dates import (
    BusinessDayConvention,
    Calendar,
    Schedule,
    ValuationDate,
    add_months,
    as_date,
    is_month_end,
)
from qfin.finance.daycount import DayCountConvention, day_count, year_fraction
from qfin.finance.distributions import EmpiricalDistribution, LogNormal, Normal
from qfin.finance.exposures import (
    FactorCVaR,
    FactorizedLossModel,
    FactorRiskProblem,
    FactorRiskSummary,
    FactorTailProbability,
    FactorTailProbabilitySummary,
    FactorVaR,
    HingeExposure,
    SparseExposureObjective,
    evaluate_factor_risk,
    evaluate_factor_tail_probability,
)
from qfin.finance.factors import FactorScenarios, GaussianFactorModel
from qfin.finance.fixed_income import (
    BondBatchAnalytics,
    CashFlow,
    FixedRateBond,
    KeyRateRiskReport,
    YieldSolveResult,
    key_rate_risk,
    par_yield,
    price_bonds,
    price_bonds_from_yield,
    yield_from_prices,
)
from qfin.finance.instruments import EuropeanCall, EuropeanOption, EuropeanPut
from qfin.finance.life import (
    LifeAssumptionSet,
    LifePolicy,
    LifeProjectionResult,
    MortalityTable,
    PolicyModelPointSet,
    ProjectionAssumptions,
    project_liabilities,
)
from qfin.finance.life_scenarios import (
    LifeScenarioResult,
    LifeSensitivityReport,
    life_sensitivities,
    project_liability_scenarios,
)
from qfin.finance.models import BlackScholes
from qfin.finance.optimization import (
    MeanVarianceProblem,
    OptimizationMethod,
    PortfolioOptimizationResult,
)
from qfin.finance.processes import GeometricBrownianMotion
from qfin.finance.rates import (
    Compounding,
    RateQuote,
    compounding_frequency,
    continuous_rate,
    convert_rate,
    discount_factor,
    rate_from_discount_factor,
)
from qfin.finance.risk import (
    CVaR,
    LossDistribution,
    RiskConfidenceInterval,
    RiskSummary,
    TailProbability,
    TailProbabilitySummary,
    VaR,
    aggregate_risk,
    bootstrap_risk_interval,
    evaluate_tail_probability,
)
from qfin.finance.scenarios import EconomicScenarioSet, RateScenarioSet

__all__ = [
    "ALMFactorAttribution",
    "ALMFactorScenarioResult",
    "ALMModel",
    "ALMPathResult",
    "ALMResult",
    "ALMScenarioResult",
    "ALMSensitivityReport",
    "AssetPortfolio",
    "BlackScholes",
    "BondBatchAnalytics",
    "BondMarketQuote",
    "BootstrapInstrument",
    "BootstrapInstrumentResult",
    "BusinessDayConvention",
    "CVaR",
    "Calendar",
    "CashFlow",
    "Compounding",
    "CurveBootstrapError",
    "CurveBootstrapReport",
    "CurveDiagnostics",
    "CurveExtrapolation",
    "CurveInterpolation",
    "CurveMarketQuote",
    "DayCountConvention",
    "Deposit",
    "EconomicScenarioSet",
    "EmpiricalDistribution",
    "EuropeanCall",
    "EuropeanOption",
    "EuropeanPut",
    "FactorCVaR",
    "FactorRiskProblem",
    "FactorRiskSummary",
    "FactorScenarios",
    "FactorTailProbability",
    "FactorTailProbabilitySummary",
    "FactorVaR",
    "FactorizedLossModel",
    "FixedRateBond",
    "GaussianFactorModel",
    "GeometricBrownianMotion",
    "HingeExposure",
    "KeyRateRiskReport",
    "LiabilityPortfolio",
    "LifeAssumptionSet",
    "LifePolicy",
    "LifeProjectionResult",
    "LifeScenarioResult",
    "LifeSensitivityReport",
    "LogNormal",
    "LossDistribution",
    "MeanVarianceProblem",
    "MortalityTable",
    "Normal",
    "OptimizationMethod",
    "PolicyModelPointSet",
    "PortfolioOptimizationResult",
    "ProjectionAssumptions",
    "RateQuote",
    "RateScenarioSet",
    "RebalancingStrategy",
    "RiskConfidenceInterval",
    "RiskSummary",
    "Schedule",
    "SimpleSwap",
    "SparseExposureObjective",
    "TailProbability",
    "TailProbabilitySummary",
    "VaR",
    "ValuationDate",
    "YieldCurve",
    "YieldSolveResult",
    "ZeroCouponInstrument",
    "add_months",
    "aggregate_risk",
    "as_date",
    "bootstrap_curve",
    "bootstrap_risk_interval",
    "compounding_frequency",
    "continuous_rate",
    "convert_rate",
    "day_count",
    "discount_factor",
    "evaluate_factor_risk",
    "evaluate_factor_tail_probability",
    "evaluate_tail_probability",
    "is_month_end",
    "key_rate_risk",
    "life_sensitivities",
    "par_yield",
    "price_bonds",
    "price_bonds_from_yield",
    "project_liabilities",
    "project_liability_scenarios",
    "rate_from_discount_factor",
    "year_fraction",
    "yield_from_prices",
]
