"""QFin public API."""

from qfin.circuits import (
    PayoffRotation,
    ProbabilityTreePreparation,
    UniformQuantilePreparation,
    WalshPayoffApproximation,
    WalshTerm,
)
from qfin.compiler import (
    CompiledPricingModel,
    CompiledRiskModel,
    ErrorBudget,
    PricingResult,
    ProblemCapabilities,
    compile,
    problem_capabilities,
)
from qfin.exceptions import (
    BackendUnavailableError,
    CompilationError,
    NativeBackendUnavailableError,
    QFinError,
    ResourceLimitError,
)
from qfin.finance import (
    ALMModel,
    ALMResult,
    ALMScenarioResult,
    AssetPortfolio,
    BlackScholes,
    BondBatchAnalytics,
    CashFlow,
    CVaR,
    EmpiricalDistribution,
    EuropeanCall,
    EuropeanPut,
    FixedRateBond,
    GeometricBrownianMotion,
    LiabilityPortfolio,
    LifePolicy,
    LifeProjectionResult,
    LogNormal,
    LossDistribution,
    MortalityTable,
    Normal,
    ProjectionAssumptions,
    RateScenarioSet,
    RiskSummary,
    YieldCurve,
    YieldSolveResult,
    aggregate_risk,
    price_bonds,
    price_bonds_from_yield,
    project_liabilities,
    yield_from_prices,
)
from qfin.representation import DistributionEncoding, encode, encode_quantiles
from qfin.system import SystemInfo, system_info
from qfin.validation import black_scholes_price

__version__ = "0.4.0"

__all__ = [
    "ALMModel",
    "ALMResult",
    "ALMScenarioResult",
    "AssetPortfolio",
    "BackendUnavailableError",
    "BlackScholes",
    "BondBatchAnalytics",
    "CVaR",
    "CashFlow",
    "CompilationError",
    "CompiledPricingModel",
    "CompiledRiskModel",
    "DistributionEncoding",
    "EmpiricalDistribution",
    "ErrorBudget",
    "EuropeanCall",
    "EuropeanPut",
    "FixedRateBond",
    "GeometricBrownianMotion",
    "LiabilityPortfolio",
    "LifePolicy",
    "LifeProjectionResult",
    "LogNormal",
    "LossDistribution",
    "MortalityTable",
    "NativeBackendUnavailableError",
    "Normal",
    "PayoffRotation",
    "PricingResult",
    "ProbabilityTreePreparation",
    "ProblemCapabilities",
    "ProjectionAssumptions",
    "QFinError",
    "RateScenarioSet",
    "ResourceLimitError",
    "RiskSummary",
    "SystemInfo",
    "UniformQuantilePreparation",
    "WalshPayoffApproximation",
    "WalshTerm",
    "YieldCurve",
    "YieldSolveResult",
    "__version__",
    "aggregate_risk",
    "black_scholes_price",
    "compile",
    "encode",
    "encode_quantiles",
    "price_bonds",
    "price_bonds_from_yield",
    "problem_capabilities",
    "project_liabilities",
    "system_info",
    "yield_from_prices",
]
