"""QFin public API."""

from qfin.circuits import (
    PayoffRotation,
    ProbabilityTreePreparation,
    UniformQuantilePreparation,
    WalshPayoffApproximation,
    WalshTerm,
)
from qfin.compiler import (
    ALMRiskMetric,
    ALMRiskResult,
    CompiledALMRiskModel,
    CompiledPricingModel,
    ErrorBudget,
    PricingResult,
    compile,
    compile_alm,
)
from qfin.exceptions import (
    BackendUnavailableError,
    CompilationError,
    QFinError,
    ResourceLimitError,
)
from qfin.finance import (
    ALMScenarioResult,
    ALMValuation,
    AssetLiabilityModel,
    BlackScholes,
    BondPosition,
    CashFlowSchedule,
    DiscountCurve,
    EmpiricalDistribution,
    EuropeanCall,
    EuropeanPut,
    FixedIncomePortfolio,
    FixedRateBond,
    GeometricBrownianMotion,
    LifeCashFlowProjection,
    LifePolicy,
    LifePolicyPortfolio,
    LogNormal,
    MortalityTable,
    Normal,
    PolicyPosition,
    TermLifePolicy,
    WholeLifePolicy,
)
from qfin.representation import DistributionEncoding, encode, encode_quantiles
from qfin.validation import black_scholes_price

__version__ = "0.4.0"

__all__ = [
    "ALMRiskMetric",
    "ALMRiskResult",
    "ALMScenarioResult",
    "ALMValuation",
    "AssetLiabilityModel",
    "BackendUnavailableError",
    "BlackScholes",
    "BondPosition",
    "CashFlowSchedule",
    "CompilationError",
    "CompiledALMRiskModel",
    "CompiledPricingModel",
    "DiscountCurve",
    "DistributionEncoding",
    "EmpiricalDistribution",
    "ErrorBudget",
    "EuropeanCall",
    "EuropeanPut",
    "FixedIncomePortfolio",
    "FixedRateBond",
    "GeometricBrownianMotion",
    "LifeCashFlowProjection",
    "LifePolicy",
    "LifePolicyPortfolio",
    "LogNormal",
    "MortalityTable",
    "Normal",
    "PayoffRotation",
    "PolicyPosition",
    "PricingResult",
    "ProbabilityTreePreparation",
    "QFinError",
    "ResourceLimitError",
    "TermLifePolicy",
    "UniformQuantilePreparation",
    "WalshPayoffApproximation",
    "WalshTerm",
    "WholeLifePolicy",
    "__version__",
    "black_scholes_price",
    "compile",
    "compile_alm",
    "encode",
    "encode_quantiles",
]
