"""QFin public API."""

from __future__ import annotations

from importlib import import_module
from importlib.metadata import PackageNotFoundError, version
from typing import Any
from warnings import warn

try:
    __version__ = version("qfin-quantum")
except PackageNotFoundError:
    # Source trees without installed package metadata deliberately use an
    # unmistakable development value instead of duplicating pyproject.toml.
    __version__ = "0+unknown"

from qfin.backends.devices import DeviceTarget, available_tested_devices
from qfin.backends.interop import (
    ProviderCapabilityReport,
    QasmExport,
    inspect_qiskit_backend,
)
from qfin.backends.noise import NoiseMitigationReport, NoiseModel
from qfin.circuits import (
    FactorizedPreparation,
    PayoffRotation,
    UniformQuantilePreparation,
    WalshPayoffApproximation,
)
from qfin.compiler import (
    CompiledFactorRiskModel,
    CompiledFactorTailModel,
    CompiledOptimizationModel,
    CompiledPricingModel,
    CompiledRiskModel,
    ErrorBudget,
    FactorQuantumObjectiveEstimate,
    FactorQuantumRiskResult,
    FactorQuantumTailResult,
    FactorQuantumVaRSearch,
    PricingResult,
    ProblemCapabilities,
    QuantumRiskResult,
    QuantumThresholdEstimate,
    QuantumVaRSearch,
    RiskErrorBudget,
    StructuredOracleErrorBudget,
    StructuredRiskErrorBudget,
    compile,
    problem_capabilities,
)
from qfin.exceptions import (
    BackendError,
    BackendUnavailableError,
    CalibrationError,
    CompilationError,
    NativeBackendUnavailableError,
    NumericalError,
    OptimizationError,
    PricingError,
    QFinError,
    QFinTypeError,
    QFinValidationError,
    ResourceLimitError,
    ScenarioError,
)
from qfin.finance import (
    ALMFactorAttribution,
    ALMFactorScenarioResult,
    ALMModel,
    ALMPathResult,
    ALMResult,
    ALMScenarioResult,
    ALMSensitivityReport,
    AssetPortfolio,
    BlackScholes,
    BondBatchAnalytics,
    BondMarketQuote,
    BootstrapInstrument,
    BootstrapInstrumentResult,
    BusinessDayConvention,
    Calendar,
    CashFlow,
    Compounding,
    CurveBootstrapError,
    CurveBootstrapReport,
    CurveDiagnostics,
    CurveExtrapolation,
    CurveInterpolation,
    CurveMarketQuote,
    CVaR,
    DayCountConvention,
    Deposit,
    EconomicScenarioSet,
    EmpiricalDistribution,
    EuropeanCall,
    EuropeanPut,
    FactorCVaR,
    FactorizedLossModel,
    FactorRiskProblem,
    FactorRiskSummary,
    FactorScenarios,
    FactorTailProbability,
    FactorTailProbabilitySummary,
    FactorVaR,
    FixedRateBond,
    GaussianFactorModel,
    GeometricBrownianMotion,
    HingeExposure,
    KeyRateRiskReport,
    LiabilityPortfolio,
    LifeAssumptionSet,
    LifePolicy,
    LifeProjectionResult,
    LifeScenarioResult,
    LifeSensitivityReport,
    LogNormal,
    LossDistribution,
    MeanVarianceProblem,
    MortalityTable,
    Normal,
    OptimizationMethod,
    PolicyModelPointSet,
    PortfolioOptimizationResult,
    ProjectionAssumptions,
    RateQuote,
    RateScenarioSet,
    RebalancingStrategy,
    RiskConfidenceInterval,
    RiskSummary,
    Schedule,
    SimpleSwap,
    SparseExposureObjective,
    TailProbability,
    TailProbabilitySummary,
    ValuationDate,
    VaR,
    YieldCurve,
    YieldSolveResult,
    ZeroCouponInstrument,
    add_months,
    aggregate_risk,
    as_date,
    bootstrap_curve,
    bootstrap_risk_interval,
    compounding_frequency,
    continuous_rate,
    convert_rate,
    day_count,
    discount_factor,
    evaluate_factor_risk,
    evaluate_factor_tail_probability,
    evaluate_tail_probability,
    is_month_end,
    key_rate_risk,
    life_sensitivities,
    par_yield,
    price_bonds,
    price_bonds_from_yield,
    project_liabilities,
    project_liability_scenarios,
    rate_from_discount_factor,
    year_fraction,
    yield_from_prices,
)
from qfin.representation import (
    AffineOutputPlan,
    AffineTransformValidation,
    BlockEncodingFeasibility,
    DistributionEncoding,
    FactorizedDistributionEncoding,
    LinearFactorTransform,
    MaterializedFactorGrid,
    QuantumObjectiveEncoding,
    StatePreparationStrategyReport,
    StructuredRiskOracleValidation,
    StructuredTailOracleValidation,
    analyze_block_encoding,
    cdf_objective,
    compare_state_preparation_strategies,
    compile_affine_transform,
    compile_structured_loss_oracle,
    encode,
    encode_gaussian_factors,
    encode_independent_factors,
    encode_quantiles,
    tail_excess_objective,
    tail_probability_objective,
    validate_affine_transform,
    validate_structured_risk_oracle,
    validate_structured_tail_oracle,
)
from qfin.resources import (
    DeviceResourceReport,
    OptimizationResourceReport,
    RiskResourceReport,
    StructuredFactorResourceReport,
    StructuredRiskResourceReport,
    StructuredTargetComparison,
    TranspiledCircuitResources,
)
from qfin.system import SystemInfo, system_info
from qfin.validation import (
    GOLDEN_BOND_CASES,
    FinancialTolerance,
    FinancialValidationCheck,
    FinancialValidationError,
    FinancialValidationReport,
    GoldenBondCase,
    ReferenceBondAnalytics,
    black_scholes_price,
    quantlib_available,
    quantlib_bond_from_yield,
    quantlib_bond_schedule,
    reference_bond_from_yield,
    validate_financial_values,
)

_DEPRECATED_TOP_LEVEL_EXPORTS: dict[str, tuple[str, str]] = {
    "IntegerHingePlan": ("qfin.representation", "IntegerHingePlan"),
    "IntegerPolynomialPlan": ("qfin.representation", "IntegerPolynomialPlan"),
    "IntegerQuadraticTerm": ("qfin.representation", "IntegerQuadraticTerm"),
    "ProbabilityTreePreparation": ("qfin.circuits", "ProbabilityTreePreparation"),
    "ReversibleAffineTransformPlan": (
        "qfin.representation",
        "ReversibleAffineTransformPlan",
    ),
    "StatePreparationCost": ("qfin.representation", "StatePreparationCost"),
    "StructuredLossOraclePlan": ("qfin.representation", "StructuredLossOraclePlan"),
    "WalshTerm": ("qfin.circuits", "WalshTerm"),
}


def __getattr__(name: str) -> Any:
    """Resolve deprecated implementation aliases for one compatibility cycle."""

    target = _DEPRECATED_TOP_LEVEL_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module 'qfin' has no attribute {name!r}")
    module_name, attribute_name = target
    warn(
        f"qfin.{name} is deprecated at the top level; import "
        f"{module_name}.{attribute_name} instead",
        DeprecationWarning,
        stacklevel=2,
    )
    value = getattr(import_module(module_name), attribute_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Include compatibility aliases in interactive discovery."""

    return sorted({*globals(), *_DEPRECATED_TOP_LEVEL_EXPORTS})


__all__ = [
    "GOLDEN_BOND_CASES",
    "ALMFactorAttribution",
    "ALMFactorScenarioResult",
    "ALMModel",
    "ALMPathResult",
    "ALMResult",
    "ALMScenarioResult",
    "ALMSensitivityReport",
    "AffineOutputPlan",
    "AffineTransformValidation",
    "AssetPortfolio",
    "BackendError",
    "BackendUnavailableError",
    "BlackScholes",
    "BlockEncodingFeasibility",
    "BondBatchAnalytics",
    "BondMarketQuote",
    "BootstrapInstrument",
    "BootstrapInstrumentResult",
    "BusinessDayConvention",
    "CVaR",
    "Calendar",
    "CalibrationError",
    "CashFlow",
    "CompilationError",
    "CompiledFactorRiskModel",
    "CompiledFactorTailModel",
    "CompiledOptimizationModel",
    "CompiledPricingModel",
    "CompiledRiskModel",
    "Compounding",
    "CurveBootstrapError",
    "CurveBootstrapReport",
    "CurveDiagnostics",
    "CurveExtrapolation",
    "CurveInterpolation",
    "CurveMarketQuote",
    "DayCountConvention",
    "Deposit",
    "DeviceResourceReport",
    "DeviceTarget",
    "DistributionEncoding",
    "EconomicScenarioSet",
    "EmpiricalDistribution",
    "ErrorBudget",
    "EuropeanCall",
    "EuropeanPut",
    "FactorCVaR",
    "FactorQuantumObjectiveEstimate",
    "FactorQuantumRiskResult",
    "FactorQuantumTailResult",
    "FactorQuantumVaRSearch",
    "FactorRiskProblem",
    "FactorRiskSummary",
    "FactorScenarios",
    "FactorTailProbability",
    "FactorTailProbabilitySummary",
    "FactorVaR",
    "FactorizedDistributionEncoding",
    "FactorizedLossModel",
    "FactorizedPreparation",
    "FinancialTolerance",
    "FinancialValidationCheck",
    "FinancialValidationError",
    "FinancialValidationReport",
    "FixedRateBond",
    "GaussianFactorModel",
    "GeometricBrownianMotion",
    "GoldenBondCase",
    "HingeExposure",
    "IntegerHingePlan",
    "IntegerPolynomialPlan",
    "IntegerQuadraticTerm",
    "KeyRateRiskReport",
    "LiabilityPortfolio",
    "LifeAssumptionSet",
    "LifePolicy",
    "LifeProjectionResult",
    "LifeScenarioResult",
    "LifeSensitivityReport",
    "LinearFactorTransform",
    "LogNormal",
    "LossDistribution",
    "MaterializedFactorGrid",
    "MeanVarianceProblem",
    "MortalityTable",
    "NativeBackendUnavailableError",
    "NoiseMitigationReport",
    "NoiseModel",
    "Normal",
    "NumericalError",
    "OptimizationError",
    "OptimizationMethod",
    "OptimizationResourceReport",
    "PayoffRotation",
    "PolicyModelPointSet",
    "PortfolioOptimizationResult",
    "PricingError",
    "PricingResult",
    "ProbabilityTreePreparation",
    "ProblemCapabilities",
    "ProjectionAssumptions",
    "ProviderCapabilityReport",
    "QFinError",
    "QFinTypeError",
    "QFinValidationError",
    "QasmExport",
    "QuantumObjectiveEncoding",
    "QuantumRiskResult",
    "QuantumThresholdEstimate",
    "QuantumVaRSearch",
    "RateQuote",
    "RateScenarioSet",
    "RebalancingStrategy",
    "ReferenceBondAnalytics",
    "ResourceLimitError",
    "ReversibleAffineTransformPlan",
    "RiskConfidenceInterval",
    "RiskErrorBudget",
    "RiskResourceReport",
    "RiskSummary",
    "ScenarioError",
    "Schedule",
    "SimpleSwap",
    "SparseExposureObjective",
    "StatePreparationCost",
    "StatePreparationStrategyReport",
    "StructuredFactorResourceReport",
    "StructuredLossOraclePlan",
    "StructuredOracleErrorBudget",
    "StructuredRiskErrorBudget",
    "StructuredRiskOracleValidation",
    "StructuredRiskResourceReport",
    "StructuredTailOracleValidation",
    "StructuredTargetComparison",
    "SystemInfo",
    "TailProbability",
    "TailProbabilitySummary",
    "TranspiledCircuitResources",
    "UniformQuantilePreparation",
    "VaR",
    "ValuationDate",
    "WalshPayoffApproximation",
    "WalshTerm",
    "YieldCurve",
    "YieldSolveResult",
    "ZeroCouponInstrument",
    "__version__",
    "add_months",
    "aggregate_risk",
    "analyze_block_encoding",
    "as_date",
    "available_tested_devices",
    "black_scholes_price",
    "bootstrap_curve",
    "bootstrap_risk_interval",
    "cdf_objective",
    "compare_state_preparation_strategies",
    "compile",
    "compile_affine_transform",
    "compile_structured_loss_oracle",
    "compounding_frequency",
    "continuous_rate",
    "convert_rate",
    "day_count",
    "discount_factor",
    "encode",
    "encode_gaussian_factors",
    "encode_independent_factors",
    "encode_quantiles",
    "evaluate_factor_risk",
    "evaluate_factor_tail_probability",
    "evaluate_tail_probability",
    "inspect_qiskit_backend",
    "is_month_end",
    "key_rate_risk",
    "life_sensitivities",
    "par_yield",
    "price_bonds",
    "price_bonds_from_yield",
    "problem_capabilities",
    "project_liabilities",
    "project_liability_scenarios",
    "quantlib_available",
    "quantlib_bond_from_yield",
    "quantlib_bond_schedule",
    "rate_from_discount_factor",
    "reference_bond_from_yield",
    "system_info",
    "tail_excess_objective",
    "tail_probability_objective",
    "validate_affine_transform",
    "validate_financial_values",
    "validate_structured_risk_oracle",
    "validate_structured_tail_oracle",
    "year_fraction",
    "yield_from_prices",
]
